# Generated by Django 5.0.3 on 2024-03-21 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gift_card_images')),
                ('description', models.TextField()),
                ('rate', models.CharField(max_length=20)),
                ('rate_for_range', models.CharField(max_length=10)),
                ('rate_for_single', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('card_dif', models.CharField(blank=True, choices=[('Dollars', 'USD'), ('Canada', 'CAD'), ('United State', 'UK'), ('Australia', 'AUD'), ('Euro', 'EUR'), ('China', 'CHF'), ('New Zeland', 'NZD')], max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(default='blank.webp', upload_to='profile_images')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='UserSellorBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_card_name', models.CharField(max_length=100)),
                ('ecode', models.TextField()),
                ('amount', models.PositiveBigIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('momo_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('momo_number', models.CharField(blank=True, max_length=100, null=True)),
                ('trans_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Declined', 'Declined'), ('Approved', 'Approved')], max_length=12, null=True)),
                ('ref', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('giftCardType', models.CharField(max_length=200)),
                ('otherGiftCardType', models.CharField(max_length=200)),
                ('giftCardAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcapp.profile')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='UserSellImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sell_gift_card_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gcapp.usersellorbuy')),
            ],
        ),
    ]
